import type { ThemeConfig, GameTheme } from "./types";

export const THEMES: Record<GameTheme, ThemeConfig> = {
  code: {
    name: "Code Vibes",
    color: "#4ecdc4",
    backIcon: "bi-display-code",
    // Logo auf der Rückseite – leg die Datei unter public/logos/code-logo.png ab
    backLogo: "./src/assets/card-back-logo.svg",
    // Bilder auf der Vorderseite – leg sie unter public/images/code/ ab
    // Dateinamen: react.png, python.png, rust.png, docker.png, ...
    images: [
      "./src/assets/code-vibes-theme-img/git-card.svg",
      "./src/assets/code-vibes-theme-img/typeScript-card.svg",
      "./src/assets/code-vibes-theme-img/javascript-card.svg",
      "./src/assets/code-vibes-theme-img/html-card.svg",
      "./src/assets/code-vibes-theme-img/vsCode-card.svg",
      "./src/assets/code-vibes-theme-img/css-card.svg",
      "./src/assets/code-vibes-theme-img/django-card.svg",
      "./src/assets/code-vibes-theme-img/angular-card.svg",
      "./src/assets/code-vibes-theme-img/terminal-card.svg",
      "./src/assets/code-vibes-theme-img/python-card.svg",
      "./src/assets/code-vibes-theme-img/github-card.svg",
      "./src/assets/code-vibes-theme-img/node.js-card.svg",
      "./src/assets/code-vibes-theme-img/bootstrap-card.svg",
      "./src/assets/code-vibes-theme-img/vue.js-card.svg",
      "./src/assets/code-vibes-theme-img/react-card.svg",
      "./src/assets/code-vibes-theme-img/sass-card.svg",
      "./src/assets/code-vibes-theme-img/sql-card.svg",
      "./src/assets/code-vibes-theme-img/firebase-card.svg",
    ],
    symbols: [
      "⚛️",
      "🐍",
      "🦀",
      "🐳",
      "🔧",
      "🌐",
      "📦",
      "🚀",
      "💾",
      "🖥️",
      "⌨️",
      "🔌",
      "🛠️",
      "📡",
      "🔗",
      "🧩",
      "🤖",
      "🧪",
    ],
  },
  gaming: {
    name: "Gaming",
    color: "#a855f7",
    backIcon: "bi-controller",
    backLogo: "/logos/gaming-logo.png",
    images: [
      "/images/gaming/mario.png",
      "/images/gaming/zelda.png",
      "/images/gaming/pokemon.png",
      "/images/gaming/minecraft.png",
      "/images/gaming/fortnite.png",
      "/images/gaming/among-us.png",
      "/images/gaming/pac-man.png",
      "/images/gaming/tetris.png",
      "/images/gaming/sonic.png",
      "/images/gaming/doom.png",
      "/images/gaming/portal.png",
      "/images/gaming/halo.png",
      "/images/gaming/gta.png",
      "/images/gaming/overwatch.png",
      "/images/gaming/apex.png",
      "/images/gaming/valorant.png",
      "/images/gaming/lol.png",
      "/images/gaming/csgo.png",
    ],
    symbols: [
      "🎮",
      "🕹️",
      "👾",
      "🏆",
      "⚔️",
      "🛡️",
      "💎",
      "🔫",
      "🎯",
      "🃏",
      "🎲",
      "🏰",
      "🧙",
      "🐉",
      "⭐",
      "🌙",
      "🔥",
      "💥",
    ],
  },
  da: {
    name: "DA Projects",
    color: "#f59e0b",
    backIcon: "bi-kanban",
    backLogo: "/logos/da-logo.png",
    images: [
      "/images/da/chart-bar.png",
      "/images/da/dashboard.png",
      "/images/da/database.png",
      "/images/da/excel.png",
      "/images/da/powerbi.png",
      "/images/da/tableau.png",
      "/images/da/python-data.png",
      "/images/da/sql.png",
      "/images/da/jupyter.png",
      "/images/da/pandas.png",
      "/images/da/spark.png",
      "/images/da/airflow.png",
      "/images/da/looker.png",
      "/images/da/dbt.png",
      "/images/da/snowflake.png",
      "/images/da/bigquery.png",
      "/images/da/jira.png",
      "/images/da/confluence.png",
    ],
    symbols: [
      "📊",
      "📈",
      "📉",
      "🗂️",
      "📋",
      "✅",
      "🔖",
      "📌",
      "🧠",
      "💡",
      "🔍",
      "📝",
      "📅",
      "🏷️",
      "🎯",
      "📐",
      "🔑",
      "📊",
    ],
  },
  food: {
    name: "Foods",
    color: "#ef4444",
    backIcon: "bi-egg-fried",
    backLogo: "/logos/food-logo.png",
    images: [
      "/images/food/pizza.png",
      "/images/food/burger.png",
      "/images/food/taco.png",
      "/images/food/ramen.png",
      "/images/food/sushi.png",
      "/images/food/salad.png",
      "/images/food/donut.png",
      "/images/food/icecream.png",
      "/images/food/cupcake.png",
      "/images/food/grapes.png",
      "/images/food/avocado.png",
      "/images/food/corn.png",
      "/images/food/strawberry.png",
      "/images/food/croissant.png",
      "/images/food/egg.png",
      "/images/food/waffle.png",
      "/images/food/pancake.png",
      "/images/food/bento.png",
    ],
    symbols: [
      "🍕",
      "🍔",
      "🌮",
      "🍜",
      "🍣",
      "🥗",
      "🍩",
      "🍦",
      "🧁",
      "🍇",
      "🥑",
      "🌽",
      "🍓",
      "🥐",
      "🍳",
      "🧇",
      "🥞",
      "🍱",
    ],
  },
};
