import type { ThemeConfig, GameTheme } from "./types";

/**
 * Registry of all available themes, keyed by {@link GameTheme}.
 *
 * Each entry provides the colour, icons, card images, and preview assets
 * for one visual theme of the game.
 */
export const THEMES: Record<GameTheme, ThemeConfig> = {
  code: {
    name: "Code Vibes",
    color: "#4ecdc4",
    backIcon: "bi-display-code",
    backLogo: "/card-back-logo.svg",
    previewImage: "/coding-vibes-settings-preview.svg",
    images: [
      "/git-card.svg",
      "/typeScript-card.svg",
      "/javascript-card.svg",
      "/html-card.svg",
      "/vsCode-card.svg",
      "/css-card.svg",
      "/django-card.svg",
      "/angular-card.svg",
      "/terminal-card.svg",
      "/python-card.svg",
      "/github-card.svg",
      "/node.js-card.svg",
      "/bootstrap-card.svg",
      "/vue.js-card.svg",
      "/react-card.svg",
      "/sass-card.svg",
      "/sql-card.svg",
      "/firebase-card.svg",
    ],
  },
  gaming: {
    name: "Gaming",
    color: "#e91e8c",
    backIcon: "",
    backLogo: "/logos/gaming-logo.png",
    previewImage: "/gaming-theme-settings-preview.svg",
    images: [
      "/circle-mask-card.svg",
      "/square-mask-card.svg",
      "/triangle-mask-card.svg",
      "/maze-card.svg",
      "/creeper-card.svg",
      "/super-mushroom-card.svg",
      "/dice-card.svg",
      "/banana-card.svg",
      "/controller-card.svg",
      "/pac-man-ghost-card.svg",
      "/coin-card.svg",
      "/snake-card.svg",
      "/level-up-card.svg",
      "/pac-man-card.svg",
      "/console-card.svg",
      "/puzzle-card.svg",
      "/playing-card.svg",
      "/play-button-card.svg",
    ],
  },
  da: {
    name: "DA Projects",
    color: "#4a8db5",
    backIcon: "bi-kanban",
    backLogo: "/card-back-logo.svg",
    previewImage: "/da-projects-settings-preview.svg",
    images: [
      "/noodle-bowl-card.svg",
      "/hot-soup-card.svg",
      "/boiled-egg-card.svg",
      "/cherry-blossom-card.svg",
      "/join-card.svg",
      "/chef-hat-card.svg",
      "/linked-square-card.svg",
      "/shopping-basket-card.svg",
      "/poké-ball-card.svg",
      "/tic-tac-toe-card.svg",
      "/exploding-emoji-card.svg",
      "/arrow-card.svg",
      "/da-bubble-card.svg",
      "/pollo-loco-card.svg",
      "/tree-canopy-card.svg",
      "/user-profile-card.svg",
      "/sharky-card.svg",
      "/curreny-exchange-card.svg",
    ],
  },
  food: {
    name: "Foods",
    color: "#f5832a",
    backIcon: "bi-egg-fried",
    backLogo: "/card-back-logo.svg",
    previewImage: "/foods-theme-settings-preview.svg",
    images: [
      "/french-fries-card.svg",
      "/pizza-slice-card.svg",
      "/sandwich-card.svg",
      "/donut-card.svg",
      "/sushi-roll-card.svg",
      "/corn-dog-card.svg",
      "/hamburger-card.svg",
      "/pretzel-card.svg",
      "/cupcake-card.svg",
      "/chocolate-cake-card.svg",
      "/pudding-card.svg",
      "/chocolate-bar-card.svg",
      "/fried-chicken-card.svg",
      "/burrito-card.svg",
      "/taco-card.svg",
      "/ice-cream-card.svg",
      "/salad-bowl-card.svg",
      "/macarons-card.svg",
    ],
  },
};
